import { useEthers } from "@usedapp/core";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const { activateBrowserWallet, account } = useEthers();

  function ConnectMetaMask() {
    activateBrowserWallet();
  }

  function SliceAddress(): string {
    const walletAddress = account?.toString();
    if (!walletAddress) {
      return "";
    }
    const slicedAddressFirst = account?.toString().slice(0, 5);
    const slicedAddressLast = account
      ?.toString()
      .slice(walletAddress.length - 4, walletAddress.length);
    return `${slicedAddressFirst}...${slicedAddressLast}`;
  }

  return (
    <div>
      <Head>
        <title>Metamask Web3 Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          display: "flex",
          alignItems: "center",
          flexDirection: "column",
          width: "100%",
        }}
      >
        <h1>MetaMask Login</h1>
        {account === undefined ? (
          <button
            style={{
              background: "white",
              color: "black",
              border: "none",
              padding: "10px",
              fontWeight: "900",
              cursor: "pointer",
            }}
            onClick={ConnectMetaMask}
          >
            Connect
          </button>
        ) : (
          <h2>{SliceAddress()}</h2>
        )}
      </main>
    </div>
  );
};

export default Home;
